// App
export const APP_RESET_STATE = 'APP:RESET_STATE';
export const APP_LOAD_STATE = 'APP:LOAD_STATE';
export const APP_SET_STATE = 'APP:SET_STATE';
export const APP_DATA_LOADED = 'APP:DATA_LOADED';

// Dialog
export const DIALOG_OPEN = 'DIALOG:OPEN';
export const DIALOG_CLOSE = 'DIALOG:CLOSE';

// Modal
export const MODAL_OPEN = 'MODAL:OPEN';
export const MODAL_CLOSE = 'MODAL:CLOSE';

// Snackbar
export const SNACKBAR_SHOW = 'SNACKBAR:SHOW';
export const SNACKBAR_HIDE = 'SNACKBAR:HIDE';
export const SNACKBAR_SET_MESSAGE = 'SNACKBAR:SET_MESSAGE';
export const SNACKBAR_CLEAR_DELAY = 'SNACKBAR:CLEAR_DELAY';

// Certificate
export const CERTIFICATE_SELECT = 'CERTIFICATE:SELECT';
export const CERTIFICATE_UPDATE = 'CERTIFICATE:UPDATE';
export const CERTIFICATE_ADD = 'CERTIFICATE:ADD';
export const CERTIFICATE_REMOVE = 'CERTIFICATE:REMOVE';
export const CERTIFICATE_DOWNLOAD = 'CERTIFICATE:DOWNLOAD';
export const CERTIFICATE_COPY = 'CERTIFICATE:COPY';

// Provider
export const PROVIDER_ADD = 'PROVIDER:ADD';
export const PROVIDER_SELECT = 'PROVIDER:SELECT';
export const PROVIDERS_UPDATE = 'PROVIDERS:UPDATE';

// Routing
export const ROUTING_PUSH = 'ROUTING:PUSH';
export const ROUTING_BACK = 'ROUTING:BACK';

// Webcrypto
export const WS_GET_KEYS = 'WS:GET_KEYS';
export const WS_GET_KEY = 'WS:GET_KEY';
export const WS_REMOVE_KEY = 'WS:REMOVE_KEY';
export const WS_GET_CERTIFICATES = 'WS:GET_CERTIFICATES';
export const WS_GET_CERTIFICATE = 'WS:GET_CERTIFICATE';
export const WS_CREATE_CSR = 'WS:CREATE_CSR';
export const WS_REMOVE_ITEM = 'WS:REMOVE_CSR';
export const WS_STATUS = 'WS:STATUS';
export const WS_DOWNLOAD_CERTIFICATE = 'WS:DOWNLOAD_CERTIFICATE';
export const WS_COPY_CERTIFICATE = 'WS:COPY_CERTIFICATE';
export const WS_GET_PROVIDERS = 'WS:GET_PROVIDERS';

// Error
export const ERROR = 'ERROR';
