export const DEFAULT = {
  id: '[[id]]',
  _id: '[[id]]',
  name: '',
  startDate: '',
  expirationDate: '',
  commonName: '',
  organization: '',
  organizationUnit: '',
  country: '',
  region: '',
  city: '',
  keyInfo: {
    algorithm: '',
    modulusBits: '',
    namedCurve: '',
    type: '',
    usages: [],
  },
  selected: false,
  type: 'certificate',
};
