export const DEFAULT = {
  id: '[[id]]',
  _id: '[[id]]',
  name: '',
  startDate: '',
  expirationDate: '',
  hostName: '',
  organization: '',
  organizationUnit: '',
  country: '',
  region: '',
  city: '',
  keyInfo: {
    createdAt: '',
    lastUsed: '',
    algorithm: '',
    size: '',
    usages: [],
  },
  selected: false,
  type: 'certificate',
};
