export const DEFAULT = {
  id: '[[id]]',
  _id: '[[id]]',
  name: '',
  commonName: '',
  organization: '',
  organizationUnit: '',
  country: '',
  region: '',
  city: '',
  keyInfo: {
    modulusBits: '',
    namedCurve: '',
    type: '',
    publicExponent: '',
    algorithm: '',
  },
  selected: false,
  type: 'request',
};
